[plugin]
prepend_fetchers = [
  { id = "git", url = "*", run = "git", group = "none" },
  { id = "git", url = "*/", run = "git", group = "none" }
]

[mgr]
linemode = "rtime"
sort_by = "natural"

[preview]
max_width = 1000
max_height = 2000

[opener]
zathura = [{ run = "zathura %s", orphan = true, desc = "Zathura" }]
papers = [{ run = "papers %s", orphan = true, desc = "Papers" }]
firefox = [{ run = "firefox %s", orphan = true, desc = "Firefox" }]
unzip = [
  { run = '''
    dir="$(dirname "$1")"
    base="$(basename "${1%.*}")"
    dest="$dir/$base"
    i=1
    while [ -e "$dest" ]; do dest="$dir/${base}_$((i++))"; done
    unzip "$1" -d "$dest"
''', for = "unix", desc = "Extract here" }
]
reveal_dir = [{ run = 'xdg-open "%d"', desc = "Reveal in Explorer" }]
extract_pass_7z = [
  { run = '7z x "$s"', block = true, desc = "Extract Password encrypted" }
]
extract_pass_zip = [
  { run = 'unzip "$s"', block = true, desc = "Extract Password encrypted" }
]

[open]
prepend_rules = [
  { mime = "application/pdf", use = ["zathura", "papers", "firefox", "reveal"] },
  { mime = "application/zip", use = ["unzip", "extract_pass_zip", "reveal_dir"] },
  { mime = "application/x-7z-compressed", use = [
    "extract_pass_7z",
    "reveal_dir",
  ] },
  { mime = "application/x-tar", use = ["reveal_dir"] },
]
