# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json

notARepository: "skip"
disableStartupPopups: true
promptToReturnFromSubprocess: false
os:
  editPreset: "nvim"
git:
  pagers:
    - colorArg: always
      # Lazygit has a bug that it will always pass dark to the pager. With
      # `--light` this can be overwritten. Tracking issue:  https://github.com/jesseduffield/lazygit/issues/4550
      pager: delta --paging=never --detect-dark-light always --side-by-side
gui:
  showCommandLog: false
  nerdFontsVersion: "3"
  statusPanelView: allBranchesLog
  theme:
    activeBorderColor:
      - blue
      - bold
    inactiveBorderColor:
      - gray
    searchingActiveBorderColor:
      - yellow
    optionsTextColor:
      - blue
    selectedLineBgColor:
      - default
    inactiveViewSelectedLineBgColor:
      - bold
    cherryPickedCommitFgColor:
      - blue
    cherryPickedCommitBgColor:
      - darkgray
    markedBaseCommitFgColor:
      - blue
    markedBaseCommitBgColor:
      - yellow
    unstagedChangesColor:
      - red
    defaultFgColor:
      - default
keybinding:
  universal:
    prevPage: <c-b>
    nextPage: <c-f>
